// Dev-only. Regenerates the bundled popular-package corpus from npm-high-impact
// (MIT, https://github.com/wooorm/npm-high-impact, upstream data ecosyste.ms).
// No runtime dependency: uses Node built-in fetch and writes a generated .ts
// module the detectors import. Run: npm run refresh:popular
//
// The corpus is download-ranked (index 0 = most downloaded), so the array index
// doubles as a popularity rank the typosquat detector uses to tier its verdict.

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../src/ecosystems/npm/data/popular-packages.ts",
);

async function main() {
  const meta = await (await fetch("https://registry.npmjs.org/npm-high-impact/latest")).json();
  const version = meta.version;
  const license = meta.license;
  const url = `https://cdn.jsdelivr.net/npm/npm-high-impact@${version}/lib/top-download.js`;
  const src = await (await fetch(url)).text();
  const mod = await import("data:text/javascript;base64," + Buffer.from(src).toString("base64"));
  const names = mod.topDownload;
  if (!Array.isArray(names) || names.length === 0) {
    throw new Error("Could not parse npm-high-impact download list");
  }

  const generatedAt = new Date().toISOString();
  const body = `// Generated by scripts/refresh-popular.mjs. Do not edit by hand.
// Source: npm-high-impact ${version} (${license}), upstream ecosyste.ms.
// Download-ranked; array index is the popularity rank (0 = most downloaded).
export const POPULAR_META = {
  source: "npm-high-impact",
  sourceVersion: ${JSON.stringify(version)},
  sourceLicense: ${JSON.stringify(license)},
  upstream: "ecosyste.ms",
  generatedAt: ${JSON.stringify(generatedAt)},
  count: ${names.length},
} as const;

export const POPULAR_NAMES: readonly string[] = ${JSON.stringify(names)};
`;

  await writeFile(OUT, body, "utf8");
  console.log(`Wrote ${names.length} names to ${OUT} (npm-high-impact ${version})`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
